# Generated by Django 5.1.4 on 2024-12-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_security_answ_user_security_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answ',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_quest',
            field=models.CharField(choices=[('QUESTION_1', 'what is your favorite movie'), ('QUESTION_2', 'what is your first animal companion'), ('QUESTION_3', "what is your mother's name"), ('QUESTION_4', 'what is your childhood nickname'), ('QUESTION_5', 'what is the name of your best teacher')], max_length=50),
        ),
    ]
