# Generated by Django 3.2.25 on 2024-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('taskDate', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('done', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
