# Generated by Django 3.2.25 on 2024-11-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0005_auto_20240920_1905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
